- name: Get JumpCloud systemKey
  shell: echo $(cat /opt/jc/jcagent.conf) | sed -n 's/.*\(\"systemKey\"\:\"[a-zA-Z0-9]*\"\).*/\1/p'
  register: jc_system_key
  changed_when: false


- name: Install the temporary Tag System script into position
  template:
    src:      "{{ jumpcloud_tag_system_template_path }}"
    dest:     "{{ jumpcloud_temp_directory }}/{{ jumpcloud_temp_tag_system_file }}"
    owner:    "{{ jumpcloud_install_script_owner }}"
    group:    "{{ jumpcloud_install_script_group }}"
    mode:     "{{ jumpcloud_install_script_mode }}"

- name:     Execute the Tag System script via the shell
  command: "./{{ jumpcloud_temp_tag_system_file }}"
  args:
    chdir: "{{ jumpcloud_temp_directory }}"
